// Edit this file to add more items.
// Fields:
// - filename: 原始檔名
// - image: 圖片路徑 (相對於 index.html)
// - objectPosition: 縮圖裁切位置 (CSS object-position，例如 "50% 70%")
// - decoration: 裝飾（字串或陣列，例如 ["一字帶","T字帶","防水台","側空","金邊"]）
// - style: 款式
// - toe: 鞋頭
// - heelStyle: 鞋跟樣式
// - heelHeight: 鞋跟高度（平底/低跟/中跟/高跟/超高跟）
// - heelHeightCm: 鞋跟高度 (cm, 可小數；可不填，頁面會自動換算 heelHeight)
// - materialSimple: 材質（麂皮/霧面皮/漆皮/亮粉）
// - material: 材質（可留原本較細分的描述；頁面會自動換算 materialSimple）
// - color: 顏色
window.SHOE_DATA = [
  {
    id: "030221-001",
    filename: "030221-001.PNG",
    image: "originals/030221-001.PNG",
    objectPosition: "50% 85%",
    decoration: ["一字帶", "防水台"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 12.5,
    material: "霧面皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-340.1",
    filename: "ABP-340.1.png",
    image: "originals/ABP-340.1.png",
    objectPosition: "50% 55%",
    decoration: ["一字帶", "T字帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "ABF-115.2",
    filename: "ABF-115.2.png",
    image: "originals/ABF-115.2.png",
    objectPosition: "70% 70%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "金屬鏡面漆皮",
    color: "銀",
  },
  {
    id: "ABW-114.1",
    filename: "ABW-114.1.png",
    image: "originals/ABW-114.1.png",
    objectPosition: "78% 58%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABW-121.1",
    filename: "ABW-121.1.png",
    image: "originals/ABW-121.1.png",
    decoration: ["防水台", "一字帶"],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "粗跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-052",
    filename: "ABW-052.png",
    image: "originals/ABW-052.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-019",
    filename: "ABW-019.PNG",
    image: "originals/ABW-019.PNG",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-080",
    filename: "ABW-080.png",
    image: "originals/ABW-080.png",
    decoration: ["防水台"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeight: "超高跟",
    materialSimple: "漆皮",
    color: "透明",
  },
  {
    id: "ABW-114",
    filename: "ABW-114.png",
    image: "originals/ABW-114.png",
    decoration: ["防水台", "一字帶", "金邊"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeight: "超高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-114.2",
    filename: "ABW-114.2.png",
    image: "originals/ABW-114.2.png",
    decoration: ["防水台", "一字帶"],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "白",
  },
  {
    id: "ABW-116",
    filename: "ABW-116.png",
    image: "originals/ABW-116.png",
    decoration: ["一字帶", "側空"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "白",
  },
  {
    id: "ABW-121",
    filename: "ABW-121.png",
    image: "originals/ABW-121.png",
    decoration: ["多帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "粗跟",
    heelHeight: "中跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-132",
    filename: "ABW-132.png",
    image: "originals/ABW-132.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "超高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-133",
    filename: "ABW-133.png",
    image: "originals/ABW-133.png",
    decoration: ["防水台", "T字帶"],
    style: "涼鞋",
    toe: "魚口",
    heelStyle: "細跟",
    heelHeight: "超高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-137",
    filename: "ABW-137.png",
    image: "originals/ABW-137.png",
    decoration: ["防水台"],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "粗跟",
    heelHeight: "超高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-176.1",
    filename: "ABW-176.1.png",
    image: "originals/ABW-176.1.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "BLK-543",
    filename: "BLK-543.png",
    image: "originals/BLK-543.png",
    objectPosition: "68% 56%",
    decoration: ["防水台"],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeightCm: 12.5,
    material: "漆皮亮面",
    color: "珊瑚粉",
  },
  {
    id: "CEAD-488.2",
    filename: "CEAD-488.2.PNG",
    image: "originals/CEAD-488.2.PNG",
    objectPosition: "82% 55%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "麂皮絨面",
    color: "桃紅",
  },
  {
    id: "DPMI-029",
    filename: "DPMI-029.PNG",
    image: "originals/DPMI-029.PNG",
    objectPosition: "78% 82%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "DPMI-061",
    filename: "DPMI-061.PNG",
    image: "originals/DPMI-061.PNG",
    objectPosition: "50% 80%",
    style: "長靴",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "DPMX-016.2",
    filename: "DPMX-016.2.png",
    image: "originals/DPMX-016.2.png",
    objectPosition: "40% 78%",
    decoration: ["防水台", "金邊"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 12.5,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "GWDOM-002.5",
    filename: "GWDOM-002.5.png",
    image: "originals/GWDOM-002.5.png",
    objectPosition: "18% 55%",
    decoration: ["側空"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "霧面皮革或麂皮感",
    color: "淺灰",
  },
  {
    id: "KDMI-059.1",
    filename: "KDMI-059.1.PNG",
    image: "originals/KDMI-059.1.PNG",
    objectPosition: "35% 65%",
    style: "長靴",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "legsjapan-1099",
    filename: "legsjapan-1099.png",
    image: "originals/legsjapan-1099.png",
    objectPosition: "35% 80%",
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "平底",
    heelHeightCm: 2.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABF-032.1",
    filename: "ABF-032.1.png",
    image: "originals/ABF-032.1.png",
    objectPosition: "70% 65%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABF-032.2",
    filename: "ABF-032.2.png",
    image: "originals/ABF-032.2.png",
    objectPosition: "28% 58%",
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "亮粉金屬感",
    color: "銀",
  },
  {
    id: "ABF-032",
    filename: "ABF-032.png",
    image: "originals/ABF-032.png",
    objectPosition: "72% 78%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABF-092.1",
    filename: "ABF-092.1.png",
    image: "originals/ABF-092.1.png",
    objectPosition: "40% 62%",
    decoration: ["防水台"],
    style: "包鞋",
    toe: "魚口",
    heelStyle: "細跟",
    heelHeightCm: 12,
    material: "麂皮絨面",
    color: "黑",
  },
  {
    id: "ABF-092",
    filename: "ABF-092.png",
    image: "originals/ABF-092.png",
    objectPosition: "52% 55%",
    decoration: ["防水台"],
    style: "長靴",
    toe: "圓頭",
    heelStyle: "粗跟",
    heelHeightCm: 11.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABF-108.1",
    filename: "ABF-108.1.PNG",
    image: "originals/ABF-108.1.PNG",
    objectPosition: "40% 82%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABF-108",
    filename: "ABF-108.PNG",
    image: "originals/ABF-108.PNG",
    objectPosition: "42% 82%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABF-115.1",
    filename: "ABF-115.1.png",
    image: "originals/ABF-115.1.png",
    objectPosition: "72% 58%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 12,
    material: "金屬鏡面漆皮",
    color: "銀",
  },
  {
    id: "ABF-115",
    filename: "ABF-115.png",
    image: "originals/ABF-115.png",
    objectPosition: "50% 60%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "粗跟",
    heelHeightCm: 9.5,
    material: "亮粉金屬感",
    color: "銀",
  },
  {
    id: "ABF-311.1",
    filename: "ABF-311.1.PNG",
    image: "originals/ABF-311.1.PNG",
    objectPosition: "55% 70%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABF-311",
    filename: "ABF-311.PNG",
    image: "originals/ABF-311.PNG",
    objectPosition: "55% 78%",
    decoration: ["鉚釘"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-053.1",
    filename: "ABP-053.1.png",
    image: "originals/ABP-053.1.png",
    objectPosition: "70% 62%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 8.5,
    material: "漆皮亮面",
    color: "桃紅",
  },
  {
    id: "ABP-053",
    filename: "ABP-053.png",
    image: "originals/ABP-053.png",
    objectPosition: "70% 70%",
    decoration: ["一字帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 11,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-229.1",
    filename: "ABP-229.1.PNG",
    image: "originals/ABP-229.1.PNG",
    objectPosition: "82% 70%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "亮粉金屬感",
    color: "銀",
  },
  {
    id: "ABP-229.2",
    filename: "ABP-229.2.PNG",
    image: "originals/ABP-229.2.PNG",
    objectPosition: "75% 72%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "ABP-229.3",
    filename: "ABP-229.3.PNG",
    image: "originals/ABP-229.3.PNG",
    objectPosition: "78% 75%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-229.4",
    filename: "ABP-229.4.PNG",
    image: "originals/ABP-229.4.PNG",
    objectPosition: "62% 78%",
    style: "長靴",
    toe: "圓頭",
    heelStyle: "粗跟",
    heelHeightCm: 9,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-229.5",
    filename: "ABP-229.5.PNG",
    image: "originals/ABP-229.5.PNG",
    objectPosition: "20% 78%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-340.2",
    filename: "ABP-340.2.png",
    image: "originals/ABP-340.2.png",
    objectPosition: "62% 58%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-340.3",
    filename: "ABP-340.3.png",
    image: "originals/ABP-340.3.png",
    objectPosition: "30% 70%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-340",
    filename: "ABP-340.png",
    image: "originals/ABP-340.png",
    objectPosition: "65% 70%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 8.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-412.1",
    filename: "ABP-412.1.png",
    image: "originals/ABP-412.1.png",
    objectPosition: "65% 82%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-412.2",
    filename: "ABP-412.2.png",
    image: "originals/ABP-412.2.png",
    objectPosition: "35% 68%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 11,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-412.3",
    filename: "ABP-412.3.png",
    image: "originals/ABP-412.3.png",
    objectPosition: "55% 68%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 11,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-412",
    filename: "ABP-412.png",
    image: "originals/ABP-412.png",
    objectPosition: "78% 62%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "ABP-466.1",
    filename: "ABP-466.1.png",
    image: "originals/ABP-466.1.png",
    objectPosition: "32% 62%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-466.2",
    filename: "ABP-466.2.png",
    image: "originals/ABP-466.2.png",
    objectPosition: "75% 60%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "亮粉金屬感",
    color: "黑",
  },
  {
    id: "ABP-466",
    filename: "ABP-466.png",
    image: "originals/ABP-466.png",
    objectPosition: "15% 80%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-481.1",
    filename: "ABP-481.1.png",
    image: "originals/ABP-481.1.png",
    objectPosition: "50% 75%",
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeightCm: 12.5,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-481.2",
    filename: "ABP-481.2.png",
    image: "originals/ABP-481.2.png",
    objectPosition: "50% 75%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 13.5,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-481.3",
    filename: "ABP-481.3.png",
    image: "originals/ABP-481.3.png",
    objectPosition: "22% 75%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-481",
    filename: "ABP-481.png",
    image: "originals/ABP-481.png",
    objectPosition: "50% 75%",
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "粗跟",
    heelHeightCm: 13,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "ABP-556",
    filename: "ABP-556.PNG",
    image: "originals/ABP-556.PNG",
    objectPosition: "15% 80%",
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeightCm: 13,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "ABP-663.1",
    filename: "ABP-663.1.png",
    image: "originals/ABP-663.1.png",
    objectPosition: "60% 72%",
    decoration: ["一字帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 11,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "ABP-663",
    filename: "ABP-663.png",
    image: "originals/ABP-663.png",
    objectPosition: "50% 72%",
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeightCm: 9,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-682.1",
    filename: "ABP-682.1.png",
    image: "originals/ABP-682.1.png",
    objectPosition: "35% 60%",
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeightCm: 8.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-682.2",
    filename: "ABP-682.2.png",
    image: "originals/ABP-682.2.png",
    objectPosition: "30% 65%",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "亮粉金屬感",
    color: "銀",
  },
  {
    id: "ABP-682.3",
    filename: "ABP-682.3.png",
    image: "originals/ABP-682.3.png",
    objectPosition: "60% 65%",
    decoration: ["踝帶", "水鑽"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-682",
    filename: "ABP-682.png",
    image: "originals/ABP-682.png",
    objectPosition: "50% 68%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "粗跟",
    heelHeightCm: 8.5,
    material: "皮革或人造皮",
    color: "淺藍",
  },
  {
    id: "ABP-705",
    filename: "ABP-705.png",
    image: "originals/ABP-705.png",
    objectPosition: "72% 60%",
    decoration: ["踝帶"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-708",
    filename: "ABP-708.png",
    image: "originals/ABP-708.png",
    objectPosition: "28% 70%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-752.1",
    filename: "ABP-752.1.png",
    image: "originals/ABP-752.1.png",
    objectPosition: "40% 78%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-752.2",
    filename: "ABP-752.2.png",
    image: "originals/ABP-752.2.png",
    objectPosition: "60% 62%",
    decoration: ["踝帶", "金扣"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-752",
    filename: "ABP-752.png",
    image: "originals/ABP-752.png",
    objectPosition: "60% 62%",
    decoration: ["防水台", "透明"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 14,
    material: "透明PVC",
    color: "透明/粉",
  },
  {
    id: "ABP-790",
    filename: "ABP-790.png",
    image: "originals/ABP-790.png",
    objectPosition: "25% 55%",
    decoration: [],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "平底",
    heelHeightCm: 2.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-800.1",
    filename: "ABP-800.1.png",
    image: "originals/ABP-800.1.png",
    objectPosition: "55% 62%",
    decoration: [],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-800.2",
    filename: "ABP-800.2.png",
    image: "originals/ABP-800.2.png",
    objectPosition: "30% 58%",
    decoration: ["待確認"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "待確認",
    color: "黑/金(待確認)",
  },
  {
    id: "ABP-800",
    filename: "ABP-800.png",
    image: "originals/ABP-800.png",
    objectPosition: "35% 62%",
    decoration: ["多帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "皮革或人造皮",
    color: "銀",
  },
  {
    id: "ABP-841.1",
    filename: "ABP-841.1.png",
    image: "originals/ABP-841.1.png",
    objectPosition: "70% 78%",
    decoration: ["踝帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 8.5,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "ABP-841",
    filename: "ABP-841.png",
    image: "originals/ABP-841.png",
    objectPosition: "30% 62%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-894",
    filename: "ABP-894.PNG",
    image: "originals/ABP-894.PNG",
    objectPosition: "50% 75%",
    decoration: ["踝帶"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-906.1",
    filename: "ABP-906.1.PNG",
    image: "originals/ABP-906.1.PNG",
    objectPosition: "55% 78%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-906.2",
    filename: "ABP-906.2.PNG",
    image: "originals/ABP-906.2.PNG",
    objectPosition: "35% 70%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-906.3",
    filename: "ABP-906.3.PNG",
    image: "originals/ABP-906.3.PNG",
    objectPosition: "55% 70%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-906",
    filename: "ABP-906.PNG",
    image: "originals/ABP-906.PNG",
    objectPosition: "75% 80%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-917.1",
    filename: "ABP-917.1.png",
    image: "originals/ABP-917.1.png",
    objectPosition: "50% 72%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 9.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-917.2",
    filename: "ABP-917.2.png",
    image: "originals/ABP-917.2.png",
    objectPosition: "65% 72%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-917",
    filename: "ABP-917.png",
    image: "originals/ABP-917.png",
    objectPosition: "65% 62%",
    decoration: ["踝帶", "一字帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "米色",
  },
  {
    id: "ABP-935.1",
    filename: "ABP-935.1.PNG",
    image: "originals/ABP-935.1.PNG",
    objectPosition: "55% 80%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-935",
    filename: "ABP-935.PNG",
    image: "originals/ABP-935.PNG",
    objectPosition: "75% 68%",
    decoration: ["金邊"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-941.1",
    filename: "ABP-941.1.PNG",
    image: "originals/ABP-941.1.PNG",
    objectPosition: "55% 75%",
    decoration: [],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "漆皮亮面",
    color: "黑",
  },
  {
    id: "ABP-941",
    filename: "ABP-941.PNG",
    image: "originals/ABP-941.PNG",
    objectPosition: "70% 78%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10.5,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-958.1",
    filename: "ABP-958.1.png",
    image: "originals/ABP-958.1.png",
    objectPosition: "35% 70%",
    decoration: [],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "亮粉金屬感",
    color: "黑",
  },
  {
    id: "ABP-958",
    filename: "ABP-958.png",
    image: "originals/ABP-958.png",
    objectPosition: "35% 70%",
    decoration: ["T字帶", "踝帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABP-984",
    filename: "ABP-984.PNG",
    image: "originals/ABP-984.PNG",
    objectPosition: "55% 80%",
    decoration: [],
    style: "長靴",
    toe: "尖頭",
    heelStyle: "粗跟",
    heelHeightCm: 9.5,
    material: "麂皮絨面",
    color: "黑",
  },
  {
    id: "ABP-993.1",
    filename: "ABP-993.1.png",
    image: "originals/ABP-993.1.png",
    objectPosition: "55% 78%",
    decoration: ["踝帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "白",
  },
  {
    id: "ABP-993",
    filename: "ABP-993.png",
    image: "originals/ABP-993.png",
    objectPosition: "35% 72%",
    decoration: ["水鑽"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeightCm: 10,
    material: "皮革或人造皮",
    color: "黑",
  },
  {
    id: "ABW-019.1",
    filename: "ABW-019.1.PNG",
    image: "originals/ABW-019.1.PNG",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-080.1",
    filename: "ABW-080.1.png",
    image: "originals/ABW-080.1.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "白",
  },
  {
    id: "ABW-080.2",
    filename: "ABW-080.2.png",
    image: "originals/ABW-080.2.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-080.3",
    filename: "ABW-080.3.png",
    image: "originals/ABW-080.3.png",
    style: "長靴",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "漆皮",
    color: "紅",
  },
  {
    id: "ABW-080.4",
    filename: "ABW-080.4.png",
    image: "originals/ABW-080.4.png",
    decoration: ["踝帶"],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "粗跟",
    heelHeight: "中跟",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-116.1",
    filename: "ABW-116.1.png",
    image: "originals/ABW-116.1.png",
    decoration: ["一字帶", "踝帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "漆皮",
    color: "透明",
  },
  {
    id: "ABW-116.2",
    filename: "ABW-116.2.png",
    image: "originals/ABW-116.2.png",
    decoration: ["踝帶"],
    style: "包鞋",
    toe: "魚口",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-116.3",
    filename: "ABW-116.3.png",
    image: "originals/ABW-116.3.png",
    decoration: ["多帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-132.1",
    filename: "ABW-132.1.png",
    image: "originals/ABW-132.1.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-132.2",
    filename: "ABW-132.2.png",
    image: "originals/ABW-132.2.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "亮粉",
    color: "金",
  },
  {
    id: "ABW-132.3",
    filename: "ABW-132.3.png",
    image: "originals/ABW-132.3.png",
    decoration: ["防水台"],
    style: "包鞋",
    heelStyle: "粗跟",
    heelHeight: "超高跟",
    materialSimple: "漆皮",
    color: "金",
  },
  {
    id: "ABW-132.4",
    filename: "ABW-132.4.png",
    image: "originals/ABW-132.4.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "白",
  },
  {
    id: "ABW-133.1",
    filename: "ABW-133.1.png",
    image: "originals/ABW-133.1.png",
    decoration: ["一字帶", "踝帶"],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "粗跟",
    heelHeight: "中跟",
    materialSimple: "霧面皮",
    color: "白",
  },
  {
    id: "ABW-133.2",
    filename: "ABW-133.2.png",
    image: "originals/ABW-133.2.png",
    decoration: ["一字帶", "踝帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-137.1",
    filename: "ABW-137.1.png",
    image: "originals/ABW-137.1.png",
    decoration: ["防水台"],
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "平底",
    heelHeight: "平底",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-176",
    filename: "ABW-176.png",
    image: "originals/ABW-176.png",
    decoration: ["防水台", "一字帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "粗跟",
    heelHeight: "超高跟",
    materialSimple: "漆皮",
    color: "銀",
  },
  {
    id: "ABW-176.2",
    filename: "ABW-176.2.png",
    image: "originals/ABW-176.2.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-182.1",
    filename: "ABW-182.1.png",
    image: "originals/ABW-182.1.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-202",
    filename: "ABW-202.PNG",
    image: "originals/ABW-202.PNG",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-202.1",
    filename: "ABW-202.1.PNG",
    image: "originals/ABW-202.1.PNG",
    decoration: ["防水台"],
    style: "包鞋",
    toe: "魚口",
    heelStyle: "細跟",
    heelHeight: "超高跟",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-202.2",
    filename: "ABW-202.2.PNG",
    image: "originals/ABW-202.2.PNG",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-208",
    filename: "ABW-208.png",
    image: "originals/ABW-208.png",
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "裸",
  },
  {
    id: "ABW-222",
    filename: "ABW-222.png",
    image: "originals/ABW-222.png",
    decoration: ["多帶"],
    style: "涼鞋",
    toe: "露趾",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-222.1",
    filename: "ABW-222.1.png",
    image: "originals/ABW-222.1.png",
    decoration: ["踝帶"],
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-222.2",
    filename: "ABW-222.2.png",
    image: "originals/ABW-222.2.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "漆皮",
    color: "黑",
  },
  {
    id: "ABW-229",
    filename: "ABW-229.png",
    image: "originals/ABW-229.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "白",
  },
  {
    id: "ABW-229.1",
    filename: "ABW-229.1.png",
    image: "originals/ABW-229.1.png",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "超高跟",
    materialSimple: "亮粉",
    color: "銀",
  },
  {
    id: "ABW-229.2",
    filename: "ABW-229.2.png",
    image: "originals/ABW-229.2.png",
    style: "包鞋",
    toe: "圓頭",
    heelStyle: "粗跟",
    heelHeight: "中跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ABW-297",
    filename: "ABW-297.PNG",
    image: "originals/ABW-297.PNG",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "黑",
  },
  {
    id: "ARA-082",
    filename: "ARA-082.PNG",
    image: "originals/ARA-082.PNG",
    style: "包鞋",
    toe: "尖頭",
    heelStyle: "細跟",
    heelHeight: "高跟",
    materialSimple: "霧面皮",
    color: "白",
  },
];

